# Generated by Django 4.2.4 on 2023-08-02 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriasPrimas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('quantidade_produzida', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UsoMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_utilizada', models.PositiveIntegerField()),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.materiasprimas')),
                ('producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.producao')),
            ],
        ),
        migrations.AddField(
            model_name='producao',
            name='materias_primas',
            field=models.ManyToManyField(through='producao.UsoMateriaPrima', to='producao.materiasprimas'),
        ),
        migrations.AddField(
            model_name='producao',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produto'),
        ),
    ]
