# Generated by Django 4.2.4 on 2023-08-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='aberto', max_length=10),
        ),
    ]
