# Generated by Django 4.2.4 on 2023-08-02 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0004_alter_pedido_data_entrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('capacidade_carga', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Roteirizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('distancia_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedidos', models.ManyToManyField(related_name='roteirizacoes', to='pedidos.pedido')),
                ('transporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.transporte')),
            ],
        ),
        migrations.CreateModel(
            name='Rastreamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrega', models.DateTimeField()),
                ('local_entrega', models.CharField(max_length=100)),
                ('pedido_relacionado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rastreamento_pedido', to='pedidos.pedido')),
            ],
        ),
    ]
