# Generated by Django 4.2.4 on 2023-08-09 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_pedido_data_entrega'),
        ('logistica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trajeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('data_entrega', models.DateTimeField()),
                ('distancia_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedidos', models.ManyToManyField(related_name='Trajeto', to='pedidos.pedido')),
            ],
        ),
        migrations.RemoveField(
            model_name='roteirizacao',
            name='pedidos',
        ),
        migrations.RemoveField(
            model_name='roteirizacao',
            name='transporte',
        ),
        migrations.RenameModel(
            old_name='Transporte',
            new_name='Veiculo',
        ),
        migrations.DeleteModel(
            name='Rastreamento',
        ),
        migrations.DeleteModel(
            name='Roteirizacao',
        ),
        migrations.AddField(
            model_name='trajeto',
            name='transporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.veiculo'),
        ),
    ]
