# Generated by Django 4.2.4 on 2023-08-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0002_trajeto_remove_roteirizacao_pedidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(default=0, max_length=7),
            preserve_default=False,
        ),
    ]
