# Generated by Django 4.2.4 on 2023-08-09 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0004_rename_nome_veiculo_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trajeto',
            old_name='transporte',
            new_name='transpotadora',
        ),
    ]
